force-app/main/default/objects/Patient_Registration__c/Patient_Registration__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yet_to_Verify</fullName>
                <default>true</default>
                <label>Yet to Verify</label>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Protocol</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient</relationshipLabel>
    <relationshipName>Patient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <label>Subject ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Year_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Birth__c</fullName>
    <label>Year of Birth</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/Study_Protocol__c.object-meta.xml
<CustomObject>
    <label>Study Protocol</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Protocol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <label>Study Protocol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PatientController.cls
/**
 * @description       : 
 * @author            : Rishab
 * @group             : 
 * @last modified on  : 09-13-2024
**/
public without sharing class PatientController {
    @AuraEnabled(cacheable=true)
    public static List<Patient_Registration__c> getPatientsByProtocol(Id protocolId) {
        return [
            SELECT Id, Name, Subject_ID__c,Year_of_Birth__c,Status__c
            FROM Patient_Registration__c
            WHERE Study_Protocol__c = :protocolId
        ];
    }
}