force-app/main/default/objects/Site_Study_Relation__c/Site_Study_Relation__c.object-meta.xml
<CustomObject>
    <label>Site Study Relation</label>
    <nameField>
        <displayFormat>SFS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Study Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Study_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Clinical_Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Study Relations</relationshipLabel>
    <relationshipName>Site_Studies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Study_Relation__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Protocol</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Site Study Relations</relationshipLabel>
    <relationshipName>Site_Studies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/Study_Protocol__c.object-meta.xml
<CustomObject>
    <label>Study Protocol</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Protocol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Protocol__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Protocol</relationshipLabel>
    <relationshipName>Study_Protocol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <label>Study Protocol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudySiteRelationTriggerHandler.cls
public class StudySiteRelationTriggerHandler extends TriggerHandler {
    public StudySiteRelationTriggerHandler() {
        this.setMaxLoopCount(4);
    }
    public override void beforeInsert(){
        checkDuplicateSiteStudy();
    }
    public override void beforeUpdate(){
        checkDuplicateSiteStudy();
    }
    public void checkDuplicateSiteStudy(){
        List<Site_Study_Relation__c> siteStudyList = (List<Site_Study_Relation__c>)Trigger.new;
        Map<Id, Site_Study_Relation__c> clinicalMap = new Map<Id,Site_Study_Relation__c>();
        Map<Id, Site_Study_Relation__c> studyMap = new Map<Id,Site_Study_Relation__c>();
        for(Site_Study_Relation__c ssr : siteStudyList){
            clinicalMap.put(ssr.Account__c, ssr);
            studyMap.put(ssr.Study_Protocol__c, ssr);
        }
        List<Site_Study_Relation__c> duplicateSiteStudy = [SELECT Account__c, Study_Protocol__c FROM Site_Study_Relation__c WHERE Account__c IN:clinicalMap.keySet() AND Study_Protocol__c IN:studyMap.keySet()];
        for(Site_Study_Relation__c ssr : duplicateSiteStudy){
            if(clinicalMap.containsKey(ssr.Account__c) && studyMap.containsKey(ssr.Study_Protocol__c)){
                clinicalMap.get(ssr.Account__c).addError('Relationship already exists.');
            }
        }
    }
}