force-app/main/default/objects/Account/fields/Apheresis_center__c.field-meta.xml
<CustomField>
    <fullName>Apheresis_center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apheresis center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Apheresis_Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>institution_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/Manufacturing_Slot__c.object-meta.xml
<CustomObject>
    <label>Manufacturing Slot</label>
    <nameField>
        <label>Manufacturing Slots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Manufacturing_Site__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manufacturing Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Manufacturing Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Manufacturing_Slots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Study_ID__c.field-meta.xml
<CustomField>
    <fullName>Study_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study ID</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Patient__r.Id , Patient__r.Subject_ID__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/Patient_Journey__c.object-meta.xml
<CustomObject>
    <label>Patient Journey</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Journey__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_Definition__r.Id , Study_Definition__r.Display_Name__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+Patient__r.Id, Patient__r.Subject_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone__c/Patient_Milestone__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Patient Milestones</relationshipLabel>
    <relationshipName>Patient_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/Patient_Milestone_Task__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Milestone Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Apheresis_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Apheresis_Shipment__c</fullName>
    <formula>Study_Milestone_Task__r.Apheresis_Shipment__c</formula>
    <label>Apheresis Shipment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>BioCair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Drug_Product_Shipment__c.field-meta.xml
<CustomField>
    <fullName>Drug_Product_Shipment__c</fullName>
    <formula>Study_Milestone_Task__r.Drug_Product_Shipment__c</formula>
    <label>Drug Product Shipment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Patient_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Milestone</label>
    <referenceTo>Patient_Milestone__c</referenceTo>
    <relationshipLabel>Patient Milestone Tasks</relationshipLabel>
    <relationshipName>Patient_Milestone_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/Patient_Milestone_Task_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone Task Form Question</label>
    <nameField>
        <displayFormat>PMTFQ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Milestone Task Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/fields/Patient_Milestone_Task__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone_Task__c</fullName>
    <label>Patient Milestone Task</label>
    <referenceTo>Patient_Milestone_Task__c</referenceTo>
    <relationshipLabel>Patient Milestone Task Form Questions</relationshipLabel>
    <relationshipName>Patient_Milestone_Task_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/Patient_Registration__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Registration__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient</relationshipLabel>
    <relationshipName>Patient_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <label>Subject ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BioCair</fullName>
            </value>
            <value>
                <fullName>Marken</fullName>
            </value>
            <value>
                <fullName>QuickStat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Patient_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Milestone</label>
    <referenceTo>Patient_Milestone__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Drug Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/recordTypes/BioCair.recordType-meta.xml
<RecordType>
    <fullName>BioCair</fullName>
    <active>true</active>
    <label>BioCair</label>
</RecordType>

force-app/main/default/objects/Shipment__c/recordTypes/Manual.recordType-meta.xml
<RecordType>
    <fullName>Manual</fullName>
    <active>true</active>
    <label>Manual</label>
</RecordType>

force-app/main/default/globalValueSets/institution_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <masterLabel>institution type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MilestoneTaskFormQuestionTriggerHandler.cls
public with sharing class MilestoneTaskFormQuestionTriggerHandler extends TriggerHandler {
    public MilestoneTaskFormQuestionTriggerHandler() {
        this.setMaxLoopCount(4);
    }
    
    public override void afterUpdate(){
        checkSubjectIdTask();
        updateMilestoneCourier();
        formStatusProtracCall();
    }    

    public void checkSubjectIdTask() {
        Set<Id> subjectIdQues = new Set<Id>();
        List<Patient_Milestone_Task_Form_Question__c> formQuestions = (List<Patient_Milestone_Task_Form_Question__c>) Trigger.new;
        for (Patient_Milestone_Task_Form_Question__c pmtfq : formQuestions) {
            if (pmtfq.Is_Subject__c) {
                subjectIdQues.add(pmtfq.Id);
            }
        }
        if (!subjectIdQues.isEmpty()) {
            try {
                List<Patient_Milestone_Task_Form_Question__c> subjectFormQuesList = [
                    SELECT Value__c, Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__c 
                    FROM Patient_Milestone_Task_Form_Question__c 
                    WHERE Id IN :subjectIdQues
                ];
                if (!subjectFormQuesList.isEmpty()) {
                    List<Patient_Registration__c> patientList = new List<Patient_Registration__c>();
                    for (Patient_Milestone_Task_Form_Question__c subques : subjectFormQuesList) {
                        if (subques.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__c != null) {
                            Patient_Registration__c p = new Patient_Registration__c(
                                Id = subques.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__c,
                                Subject_ID__c = subques.Value__c
                            );
                            patientList.add(p);
                        }
                    }
                    if (!patientList.isEmpty()) {
                        update patientList;
                    }
                }
            } catch (DmlException dmlEx) {
                System.debug('DML Exception: ' + dmlEx.getMessage());
            } catch (Exception ex) {
                System.debug('Exception: ' + ex.getMessage());
            }
        }
    }
    

    public void formStatusProtracCall(){
        List<Patient_Milestone_Task_Form_Question__c> formQuestions = (List<Patient_Milestone_Task_Form_Question__c>)Trigger.new;
        for(Patient_Milestone_Task_Form_Question__c pmtfq : formQuestions){
            if(pmtfq.Value__c == 'QC Completed'){
                // createDrugTypeShipment(pmtfq.Id);
            }else if(pmtfq.Value__c == 'Shipped to Clinical Site'){
                // System.enqueueJob(new IntegrationHandler('Protrac_DP_Receipt', 'PROTRAC', pmtfq.Id));
            }
        }
    }

    public void createDrugTypeShipment(String recordId) {
        try {
            List<Patient_Milestone_Task_Form_Question__c> formQuestions = [
                SELECT  Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__c, Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Study_Definition__c, 
                       Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__r.Clinical_Site__c,
                       Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Id,
                       Patient_Milestone_Task__r.Patient_Milestone__r.Id
                FROM Patient_Milestone_Task_Form_Question__c 
                WHERE Id = :recordId
            ];
            if (!formQuestions.isEmpty()) {
                Patient_Milestone_Task_Form_Question__c pmtfq = formQuestions.get(0);
                List<Account> accountList = [
                    SELECT Id, Name, Study__c, BillingCity, BillingCountry, BillingPostalCode, BillingState, BillingStreet,
                           Apheresis_center__r.BillingCity, Apheresis_center__r.BillingCountry, Apheresis_center__r.BillingPostalCode, 
                           Apheresis_center__r.BillingState, Apheresis_center__r.BillingStreet
                    FROM Account 
                    WHERE Id = :pmtfq.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__r.Clinical_Site__c
                ];
                if (!accountList.isEmpty()) {
                    Account acc = accountList.get(0);
                    Manufacturing_Slot__c manuSite = [
                        SELECT Manufacturing_Site__c, Manufacturing_Site__r.BillingCity, Manufacturing_Site__r.BillingStreet, 
                               Manufacturing_Site__r.BillingState, Manufacturing_Site__r.BillingCountry, Manufacturing_Site__r.BillingPostalCode 
                        FROM Manufacturing_Slot__c 
                        WHERE Study_ID__c = :pmtfq.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Study_Definition__c 
                              AND Booking_Status__c = 'Booked' 
                              AND Clinical_Site__c = :acc.Id
                              AND Patient__c =: pmtfq.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Patient__c
                        LIMIT 1
                    ];
                    
                    Shipment__c ship = new Shipment__c();
                    ship.Type__c = 'Drug Product';
                    ship.Patient_Journey__c = pmtfq.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__r.Id;
                    ship.Patient_Milestone__c = pmtfq.Patient_Milestone_Task__r.Patient_Milestone__r.Id;
                    
                    ship.RecordTypeId = Schema.getGlobalDescribe().get('Shipment__c')
                        .getDescribe()
                        .getRecordTypeInfosByName()
                        .get('BioCair')
                        .getRecordTypeId();
                    PatientMilestoneTaskTriggerHandler.setAddressFields(ship, acc, manuSite);
                    insert ship;
                }
            }
        } catch (DmlException dmlEx) {
            System.debug('DML Exception: ' + dmlEx.getMessage());
        } catch (QueryException qEx) {
            System.debug('Query Exception: ' + qEx.getMessage());
        } catch (Exception ex) {
            System.debug('General Exception: ' + ex.getMessage());
        }
    }
    
    public void updateMilestoneCourier() {
        try {
            List<Patient_Milestone_Task_Form_Question__c> formQuestions = (List<Patient_Milestone_Task_Form_Question__c>) Trigger.new;
            List<Patient_Milestone_Task_Form_Question__c> queriedQuestions = [
                SELECT Id, Value__c, Patient_Milestone_Task__r.Apheresis_Shipment__c, Patient_Milestone_Task__r.Drug_Product_Shipment__c, 
                       Patient_Milestone_Task__r.Id 
                FROM Patient_Milestone_Task_Form_Question__c 
                WHERE Id IN :formQuestions
            ];
            List<Patient_Milestone_Task__c> patientMilestoneTasks = new List<Patient_Milestone_Task__c>();
            for (Patient_Milestone_Task_Form_Question__c fq : queriedQuestions) {
                if ((fq.Patient_Milestone_Task__r.Apheresis_Shipment__c || fq.Patient_Milestone_Task__r.Drug_Product_Shipment__c) && 
                    (fq.Value__c == 'BioCair' || fq.Value__c == 'Manual')) {
                    Patient_Milestone_Task__c pmt = new Patient_Milestone_Task__c();
                    pmt.Id = fq.Patient_Milestone_Task__r.Id;
                    pmt.Courier__c = fq.Value__c;
                    patientMilestoneTasks.add(pmt);
                }
            }
            if (!patientMilestoneTasks.isEmpty()) {
                update patientMilestoneTasks;
            }
        } catch (DmlException dmlEx) {
            System.debug('DML Exception: ' + dmlEx.getMessage());
        } catch (Exception ex) {
            System.debug('General Exception: ' + ex.getMessage());
        }
    }
}