force-app/main/default/objects/Account/fields/Apheresis_center__c.field-meta.xml
<CustomField>
    <fullName>Apheresis_center__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apheresis center</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Apheresis_Center</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Person_to_contact__c.field-meta.xml
<CustomField>
    <fullName>Person_to_contact__c</fullName>
    <label>Person to contact</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/Manufacturing_Slot__c.object-meta.xml
<CustomObject>
    <label>Manufacturing Slot</label>
    <nameField>
        <label>Manufacturing Slots Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Manufacturing Slots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Booking_Status__c.field-meta.xml
<CustomField>
    <fullName>Booking_Status__c</fullName>
    <label>Booking Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Manufacturing_Site__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manufacturing Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Manufacturing Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Manufacturing_Slots1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Study_ID__c.field-meta.xml
<CustomField>
    <fullName>Study_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study ID</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Manufacturing Slots</relationshipLabel>
    <relationshipName>Manufacturing_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manufacturing_Slot__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_ID__r.Id ,  Study_ID__r.Display_Name__c , &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study Protocol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/Patient_Journey__c.object-meta.xml
<CustomObject>
    <label>Patient Journey</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Journey__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study__c.field-meta.xml
<CustomField>
    <fullName>Study__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_Definition__r.Id , Study_Definition__r.Display_Name__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_Definition__r.Id , Study_Definition__r.Display_Name__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study Protocol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/Shipment_Container_Detail__c.object-meta.xml
<CustomObject>
    <label>Shipment Container Detail</label>
    <nameField>
        <displayFormat>SC -{0000}</displayFormat>
        <label>Shipment Container Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Container Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Commodity_Library_Id__c.field-meta.xml
<CustomField>
    <fullName>Commodity_Library_Id__c</fullName>
    <label>Commodity Library Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Package_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Package_Quantity__c</fullName>
    <label>Package Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Package_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Package_Type_Id__c</fullName>
    <label>Package Type Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Protocol</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Shipment Container Details</relationshipLabel>
    <relationshipName>Shipment_Container_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Temperature_Id__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Id__c</fullName>
    <label>Temperature Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Type_Of_Goods__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Goods__c</fullName>
    <label>Type Of Goods</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment_Container_Detail__c/fields/Weight_Unit_Of_Measure_Id__c.field-meta.xml
<CustomField>
    <fullName>Weight_Unit_Of_Measure_Id__c</fullName>
    <label>Weight Unit Of Measure Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/Study_Protocol__c.object-meta.xml
<CustomObject>
    <label>Study Protocol</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Protocol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Protocol__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clinical Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <label>Study Protocol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BiocairAPIService.cls
public with sharing class BiocairAPIService {

    public static String generateShipmentJson(String recordId) {
        try {
            Shipment__c ship = [SELECT Id, Patient_Journey__r.Patient__c, Patient_Journey__r.Study_Definition__c, 
                                       Patient_Journey__r.Clinical_Site__r.Person_to_contact__c, 
                                       Patient_Journey__r.Clinical_Site__r.Apheresis_center__r.Person_to_contact__c, 
                                       Patient_Journey__r.Clinical_Site__r.Study__c, 
                                       Patient_Journey__r.Clinical_Site__r.Apheresis_center__r.Name, 
                                       CreatedDate, Dropoff_Address__CountryCode__s, Dropoff_Address__StateCode__s, 
                                       Dropoff_Address__PostalCode__s, Dropoff_Address__City__s, Dropoff_Address__Street__s, 
                                       Pickup_Address__CountryCode__s, Pickup_Address__StateCode__s, Pickup_Address__City__s, 
                                       Pickup_Address__PostalCode__s, Pickup_Address__Street__s 
                                FROM Shipment__c 
                                WHERE Id = :recordId 
                                LIMIT 1];
            if (ship != null) {
                Manufacturing_Slot__c manuSite = [SELECT Manufacturing_Site__r.Name, Manufacturing_Site__r.Person_to_contact__c 
                                                  FROM Manufacturing_Slot__c 
                                                  WHERE Study_ID__c = :ship.Patient_Journey__r.Study_Definition__c 
                                                  AND Booking_Status__c = 'Booked' 
                                                  AND Clinical_Site__c = :ship.Patient_Journey__r.Clinical_Site__r.Id 
                                                  AND Patient__c = :ship.Patient_Journey__r.Patient__c 
                                                  LIMIT 1];
                List<Shipment_Container_Detail__c> shipmentContainers = [SELECT Id, Commodity_Library_Id__c, Temperature_Id__c, 
                                                                               Package_Quantity__c, Package_Type_Id__c, 
                                                                               Weight_Unit_Of_Measure_Id__c, Weight__c, 
                                                                               Type_Of_Goods__c 
                                                                        FROM Shipment_Container_Detail__c 
                                                                        WHERE Study_Protocol__c = :ship.Patient_Journey__r.Clinical_Site__r.Study__c];

                ShipmentRequestWrapper sw = new ShipmentRequestWrapper();
                sw.OrderDate = ship.CreatedDate;
                sw.FirstName = getFirstName(ship.Patient_Journey__r.Clinical_Site__r.Person_to_contact__c);
                sw.FamilyName = getLastName(ship.Patient_Journey__r.Clinical_Site__r.Person_to_contact__c);
                sw.consignor = new ShipmentRequestWrapper.Consignor();
                sw.consignor.firstName = getFirstName(ship.Patient_Journey__r.Clinical_Site__r.Apheresis_center__r.Person_to_contact__c);
                sw.consignor.familyName = getLastName(ship.Patient_Journey__r.Clinical_Site__r.Apheresis_center__r.Person_to_contact__c);
                sw.consignor.address = setAddress(ship.Patient_Journey__r.Clinical_Site__r.Apheresis_center__r.Name,
                                                  ship.Pickup_Address__Street__s, ship.Pickup_Address__City__s, 
                                                  ship.Pickup_Address__PostalCode__s, ship.Pickup_Address__CountryCode__s, 
                                                  ship.Pickup_Address__StateCode__s);
                
                sw.consignee = new ShipmentRequestWrapper.Consignee();
                sw.consignee.firstName = getFirstName(manuSite.Manufacturing_Site__r.Person_to_contact__c);
                sw.consignee.familyName = getLastName(manuSite.Manufacturing_Site__r.Person_to_contact__c);
                sw.consignee.address = setAddress(manuSite.Manufacturing_Site__r.Name,
                                                  ship.Dropoff_Address__Street__s, ship.Dropoff_Address__City__s, 
                                                  ship.Dropoff_Address__PostalCode__s, ship.Dropoff_Address__CountryCode__s, 
                                                  ship.Dropoff_Address__StateCode__s);
                
                sw.goodItems = new List<ShipmentRequestWrapper.GoodItem>();
                for (Shipment_Container_Detail__c sc : shipmentContainers) {
                    ShipmentRequestWrapper.GoodItem good = new ShipmentRequestWrapper.GoodItem();
                    good.commodityLibraryId = (Integer) sc.Commodity_Library_Id__c;
                    good.packageQuantity = (Integer) sc.Package_Quantity__c;
                    good.packageTypeId = (Integer) sc.Package_Type_Id__c;
                    good.temperatureId = (Integer) sc.Temperature_Id__c;
                    good.weight = (Integer) sc.Weight__c;
                    good.weightunitofmeasureId = (Integer) sc.Weight_Unit_Of_Measure_Id__c;
                    good.typeofgoods = sc.Type_Of_Goods__c;
                    sw.goodItems.add(good);
                }
                return JSON.serializePretty(sw, true);
            }

            return null;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    private static String getFirstName(String fullName) {
        if (String.isNotBlank(fullName)) {
            List<String> nameParts = fullName.split(' ');
            return nameParts.size() > 0 ? nameParts[0] : null;
        }
        return null;
    }
    private static String getLastName(String fullName) {
        if (String.isNotBlank(fullName)) {
            List<String> nameParts = fullName.split(' ');
            return nameParts.size() > 1 ? nameParts[nameParts.size() - 1] : null;
        }
        return null;
    }
    private static ShipmentRequestWrapper.Address setAddress(String name, String street, String city, 
                                                             String postalCode, String countryCode, String stateCode) {
        ShipmentRequestWrapper.Address address = new ShipmentRequestWrapper.Address();
        address.name = name;
        address.address1 = street;
        address.townCity = city;
        address.postcode = postalCode;
        address.countryCode = countryCode;
        address.state = stateCode;
        return address;
    }
}