force-app/main/default/objects/Account/fields/Site_ID__c.field-meta.xml
<CustomField>
    <fullName>Site_ID__c</fullName>
    <label>Site ID Number</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>institution_type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/Patient_Journey__c.object-meta.xml
<CustomObject>
    <label>Patient Journey</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Journey__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/COI__c.field-meta.xml
<CustomField>
    <fullName>COI__c</fullName>
    <label>COI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_Definition__r.Id , Study_Definition__r.Display_Name__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study Protocol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+Patient__r.Id, Patient__r.Subject_ID__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subject ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Year_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Birth__c</fullName>
    <formula>Patient__r.Year_of_Birth__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year of Birth</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone__c/Patient_Milestone__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Patient Milestones</relationshipLabel>
    <relationshipName>Patient_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/Patient_Milestone_Task__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone Task</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patient Milestone Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>BioCair</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task__c/fields/Patient_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Milestone</label>
    <referenceTo>Patient_Milestone__c</referenceTo>
    <relationshipLabel>Patient Milestone Tasks</relationshipLabel>
    <relationshipName>Patient_Milestone_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/Patient_Milestone_Task_Form_Question__c.object-meta.xml
<CustomObject>
    <label>Patient Milestone Task Form Question</label>
    <nameField>
        <displayFormat>PMTFQ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Milestone Task Form Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/fields/Patient_Milestone_Task__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone_Task__c</fullName>
    <label>Patient Milestone Task</label>
    <referenceTo>Patient_Milestone_Task__c</referenceTo>
    <relationshipLabel>Patient Milestone Task Form Questions</relationshipLabel>
    <relationshipName>Patient_Milestone_Task_Form_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Patient_Milestone_Task_Form_Question__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/Patient_Registration__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Registration__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient</relationshipLabel>
    <relationshipName>Patient_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Protocol</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient</relationshipLabel>
    <relationshipName>Patient</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Subject_ID__c.field-meta.xml
<CustomField>
    <fullName>Subject_ID__c</fullName>
    <label>Subject ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/fields/Year_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Birth__c</fullName>
    <label>Year of Birth</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Shipment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Courier__c.field-meta.xml
<CustomField>
    <fullName>Courier__c</fullName>
    <label>Courier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BioCair</fullName>
            </value>
            <value>
                <fullName>Marken</fullName>
            </value>
            <value>
                <fullName>QuickStat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <label>Order ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Patient_Journey__c.field-meta.xml
<CustomField>
    <fullName>Patient_Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Journey</label>
    <referenceTo>Patient_Journey__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Patient_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Patient_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient Milestone</label>
    <referenceTo>Patient_Milestone__c</referenceTo>
    <relationshipLabel>Shipment</relationshipLabel>
    <relationshipName>Shipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Tracking_ID__c.field-meta.xml
<CustomField>
    <fullName>Tracking_ID__c</fullName>
    <label>Tracking ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apheresis</fullName>
            </value>
            <value>
                <fullName>Drug Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/Study_Protocol__c.object-meta.xml
<CustomObject>
    <label>Study Protocol</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Protocol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Protocol__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clinical Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <label>Study Protocol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol_Description__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol_Description__c</fullName>
    <label>Study Protocol Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/institution_type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Clinical</fullName>
    </customValue>
    <customValue>
        <fullName>Manufacturing</fullName>
    </customValue>
    <masterLabel>institution type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProtracAPIService.cls
public with sharing class ProtracAPIService {
    public static String createShipmentRequest(Id recordId){
        // List<Shipment__c> shipmentList = [SELECT Id,Name, Patient_Journey__r.COI__c,Courier__c,Dropoff_Address__StateCode__s, Tracking_ID__c FROM Shipment__c WHERE ID = :recordId LIMIT 1];
        // if(!shipmentList.isEmpty()){
        //     ProtracRequestWrapper.APHShipmentWrapper shipAph = new ProtracRequestWrapper.APHShipmentWrapper();
        //     Shipment__c ship = shipmentList.get(0);
        //     shipAph.COI = ship.Patient_Journey__r.COI__c;
        //     shipAph.ShipmentID = ship.Name;
        //     shipAph.TrackingID = ship.Tracking_ID__c;
        //     shipAph.ShipmentVendor = ship.Courier__c;
        //     shipAph.ShippingAddress = ship.Dropoff_Address__StateCode__s;
        //     shipAph.ExpectedArrivalDate = System.today().addDays(10);
        //     return JSON.serializePretty(shipAph,true);
        // }
        return null;
    }

    public static String createStudy(Id recordId){
        List<Study_Protocol__c> protocolList = [SELECT Display_Name__c, Study_Protocol_Description__c FROM Study_Protocol__c WHERE Id =: recordId];
        if(!protocolList.isEmpty()){
            ProtracRequestWrapper.StudyWrapper wrapper = new ProtracRequestWrapper.StudyWrapper();
            wrapper.StudyProtocolNumber = protocolList[0].Display_Name__c;
            wrapper.StudyProtocolNumberDescription = protocolList[0].Study_Protocol_Description__c;
            return JSON.serialize(wrapper);
        }
        return null;
    }
    public static String createSite(Id recordId){
        List<Account> accountList = [SELECT RecordTypeId, Name, Site_ID__c FROM Account WHERE Id =: recordId];
        if(!accountList.isEmpty()){
            ProtracRequestWrapper.SiteWrapper wrapper = new ProtracRequestWrapper.SiteWrapper();
            wrapper.SiteCode = accountList[0].Site_ID__c;
            if(accountList[0].RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByName().get('Clinical Site').getRecordTypeId()){
                wrapper.SiteTypeID = 1;
            }else if(accountList[0].RecordTypeId == Schema.SObjectType.Account.getRecordTypeInfosByName().get('Manufacturing Site').getRecordTypeId()){
                wrapper.SiteTypeID = 2;
            }
            wrapper.SiteName = accountList[0].Name;
            return JSON.serialize(wrapper);
        }
        return null;
    }
    public static String createPatientRegistrationRequest(Id recordId){
        ProtracRequestWrapper.PatientRegistration wrapper = new ProtracRequestWrapper.PatientRegistration();
        List<Shipment__c> shipList = [SELECT Id, Patient_Journey__r.Study_Definition__r.Name ,Patient_Journey__r.Clinical_Site__r.Site_ID__c, Patient_Journey__r.Patient__r.Year_of_Birth__c, Patient_Journey__r.COI__c, Courier__c, Order_Id__c, Patient_Journey__r.Patient__r.Subject_ID__c, Dropoff_Address__StateCode__s, Tracking_ID__c FROM Shipment__c WHERE ID = :recordId LIMIT 1];
        if(!shipList.isEmpty()) {
            Shipment__c ship = shipList.get(0);
            List<Patient_Milestone_Task_Form_Question__c> formSubjectQuestions = [SELECT Value__c, Is_Subject__c FROM Patient_Milestone_Task_Form_Question__c WHERE Is_Subject__c = true AND Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__c =:ship.Patient_Journey__r.Id];

            List<Patient_Milestone_Task_Form_Question__c> formDinQuestions = [SELECT Value__c, Is_DIN__c FROM Patient_Milestone_Task_Form_Question__c WHERE Is_DIN__c = true AND Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__c =:ship.Patient_Journey__r.Id];

            wrapper.subjectId = !formSubjectQuestions.isEmpty()?formSubjectQuestions.get(0).Value__c:null;
            wrapper.coi = ship.Patient_Journey__r.COI__c;
            // wrapper.DIN = Integer.valueOf(!formDinQuestions.isEmpty()?formDinQuestions.get(0).Value__c:null);
            wrapper.YOB = ship.Patient_Journey__r.Patient__r.Year_of_Birth__c;
            wrapper.MFGSiteID = '';
            wrapper.ClinicalSiteID = ship.Patient_Journey__r.Clinical_Site__r.Site_ID__c;
            wrapper.studyProtocolName = ship.Patient_Journey__r.Study_Definition__r.Name;
            wrapper.shipmentId = ship.Tracking_ID__c;
            wrapper.orderId = Integer.valueOf(ship.Order_Id__c);
            wrapper.ExpectedShipmentDate = System.today();
            wrapper.ExpectedArrivalDate = System.today().addDays(8);
            return JSON.serializePretty(wrapper,true);
        }
        return null;
    }

    public static String createDPBookingRequest(Id recordId){
        ProtracRequestWrapper.DPBookingWrapper dpBook = new ProtracRequestWrapper.DPBookingWrapper();        
        List<Shipment__c> shipmentList = [SELECT Id, Patient_Journey__r.COI__c, Tracking_ID__c FROM Shipment__c WHERE ID = :recordId LIMIT 1];
        if(!shipmentList.isEmpty()){
            Shipment__c ship = shipmentList.get(0);
            dpBook.COI = ship.Patient_Journey__r.COI__c;
            dpBook.ShipmentID = ship.Tracking_ID__c;
            dpBook.ExpectedDeliveryDate = System.today().addDays(6);
            dpBook.ExpectedPickupDate = System.today();
            return JSON.serializePretty(dpBook,true);
        }
        return null;
    }

    public static String createManufacturingStatusRequest(Id recordId){
        return null; 
    }

    public static String createDPReceiptRequest(Id recordId){
        List<Patient_Milestone_Task_Form_Question__c> formQuestions = [SELECT Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__c FROM Patient_Milestone_Task_Form_Question__c WHERE Id =: recordId];
        if(!formQuestions.isEmpty()){
            Patient_Milestone_Task_Form_Question__c ques = formQuestions.get(0);
            List<Shipment__c> shipmentList = [SELECT CreatedDate, Tracking_ID__c FROM Shipment__c WHERE Patient_Journey__c =: ques.Patient_Milestone_Task__r.Patient_Milestone__r.Patient_Journey__c AND Type__c = 'Drug Product'];
            if(!shipmentList.isEmpty()){
                ProtracRequestWrapper.DPReceiptWrapper dpReceipt = new ProtracRequestWrapper.DPReceiptWrapper();
                Shipment__c ship = shipmentList.get(0);
                dpReceipt.shipmentId = ship.Tracking_ID__c;
                dpReceipt.ReceiptDate = System.today();
                dpReceipt.ConditionOfShipment = 'Good';
                return JSON.serializePretty(dpReceipt,true);
            }
        }
        return null;
    }
}