force-app/main/default/objects/Patient_Journey__c/Patient_Journey__c.object-meta.xml
<CustomObject>
    <label>Patient Journey</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Journey__c/fields/COI__c.field-meta.xml
<CustomField>
    <fullName>COI__c</fullName>
    <label>COI</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Patient</label>
    <referenceTo>Patient_Registration__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Registration__c/Patient_Registration__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Patient ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Registration__c/fields/Is_Patient_Journey_Started__c.field-meta.xml
<CustomField>
    <fullName>Is_Patient_Journey_Started__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Patient Journey Started</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PatientJourneyTriggerHandler.cls
public class PatientJourneyTriggerHandler extends TriggerHandler {

    public PatientJourneyTriggerHandler() {
      this.setMaxLoopCount(4);
    }
    
    public override void afterInsert() {
        List<Patient_Registration__c> patients = new List<Patient_Registration__c>();
        List<Patient_Journey__c> patientJourneyList = new List<Patient_Journey__c>();
        for(Sobject s : Trigger.new){
            Patient_Journey__c pj = (Patient_Journey__c) s;
            if(pj.Study_Definition__c != null) {
                patientJourneyList.add(pj);
            }
            if(pj.Patient__c != null){
                Patient_Registration__c pr = new Patient_Registration__c(Id=pj.Patient__c, Is_Patient_Journey_Started__c = true);
                patients.add(pr);
            }
        }
        if(!patientJourneyList.isEmpty()){
            PatientJourneyTriggerService.createPaitentJourneyData(patientJourneyList);
            if(!patients.isEmpty()){
                update patients;
            }
        }     
    }

    public override void afterUpdate() {
        List<Patient_Journey__c> definitionChangePJList = new List<Patient_Journey__c>();
        // List<Patient_Journey__c> coiUpdateList = new List<Patient_Journey__c>();
        for(Sobject s : Trigger.new){
            Patient_Journey__c pj = (Patient_Journey__c) s;
            if(Trigger.oldMap.containsKey(pj.Id) && pj.Study_Definition__c != null && pj.Study_Definition__c != ( (Patient_Journey__c) Trigger.oldMap.get(pj.Id)).Study_Definition__c) {
                definitionChangePJList.add(pj);
            }
            // if(Trigger.oldMap.containsKey(pj.Id) && pj.COI__c != null && pj.COI__c != ( (Patient_Journey__c) Trigger.oldMap.get(pj.Id)).COI__c) {
            //     coiUpdateList.add(pj);
            // }    
        }
        if(!definitionChangePJList.isEmpty()){
            PatientJourneyTriggerService.createPaitentJourneyData(definitionChangePJList);
        }    
        // if(!coiUpdateList.isEmpty()){
        //     PatientJourneyTriggerService.sendCOIDetailsToProtrac(coiUpdateList);
        // }    
    }
}