force-app/main/default/objects/Contact/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yet to Verify</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/Patient_Journey__c.object-meta.xml
<CustomObject>
    <label>Patient Journey</label>
    <nameField>
        <displayFormat>PJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Journey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient_Journey__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Clinical Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Current_Stage__c.field-meta.xml
<CustomField>
    <fullName>Current_Stage__c</fullName>
    <label>Current Stage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Definition__c.field-meta.xml
<CustomField>
    <fullName>Study_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Definition</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Patient Journey</relationshipLabel>
    <relationshipName>Patient_Journey</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patient_Journey__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;+ Study_Definition__r.Id , Study_Definition__r.Display_Name__c, &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Study Protocol</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Study_Relation__c/Site_Study_Relation__c.object-meta.xml
<CustomObject>
    <label>Site Study Relation</label>
    <nameField>
        <displayFormat>SFS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Study Relations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Study_Relation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Clinical_Site</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Study Relations</relationshipLabel>
    <relationshipName>Site_Studies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Study_Relation__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Study Protocol</label>
    <referenceTo>Study_Protocol__c</referenceTo>
    <relationshipLabel>Site Study Relations</relationshipLabel>
    <relationshipName>Site_Studies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/Study_Protocol__c.object-meta.xml
<CustomObject>
    <label>Study Protocol</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Study Protocol</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Study_Protocol__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Study Protocol</relationshipLabel>
    <relationshipName>Study_Protocol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Clinical_Site__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clinical Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Study_Protocol__c.field-meta.xml
<CustomField>
    <fullName>Study_Protocol__c</fullName>
    <label>Study Protocol</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Study_Protocol__c/fields/Verify_By__c.field-meta.xml
<CustomField>
    <fullName>Verify_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verify By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Study_Protocol</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SiteHomeController.cls
public without sharing class SiteHomeController {
    @AuraEnabled(cacheable = true)
    public static List<StudyProtocolWrapper> getStudyProtocolOptions() { 
        try {
            List<StudyProtocolWrapper> wrapperList = new List<StudyProtocolWrapper>();
            List<User> users = [select id, contactId, Contact.AccountId from User where id = : UserInfo.getUserId() LIMIT 1];
            if(!users.isEmpty()) {
                for(Site_Study_Relation__c ssr : [SELECT Id, Study_Protocol__r.Id, Study_Protocol__r.Display_Name__c FROM Site_Study_Relation__c WHERE Account__c = :users[0].Contact.AccountId]){
                    StudyProtocolWrapper wrapper = new StudyProtocolWrapper();
                    wrapper.name = ssr.Study_Protocol__r.Display_Name__c;
                    wrapper.studyId = ssr.Study_Protocol__r.id;
                    wrapperList.add(wrapper);
                }
            }
            return wrapperList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class StudyProtocolWrapper {
        @AuraEnabled
        public String name{get; set;}
        @AuraEnabled
        public String studyId{get; set;}
    }

    @AuraEnabled(cacheable=true)
    public static JourneyOverviewDetails getJourneyOverview(String studyId) {
        JourneyOverviewDetails details = new JourneyOverviewDetails();
        try {
            List<User> users = [SELECT Id, ContactId, Contact.AccountId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
            if (!users.isEmpty()) {
                String clinicalSiteId = users[0].Contact.AccountId;
                List<AggregateResult> results = [SELECT COUNT(Id) mileCount, Current_Stage__c FROM Patient_Journey__c WHERE Clinical_Site__c =  :clinicalSiteId AND Study_Definition__c = :studyId GROUP BY Current_Stage__c ];

                List<AggregateResult> pjAggList = [
                    SELECT COUNT(Id) pjCount 
                    FROM Patient_Journey__c 
                    WHERE Clinical_Site__c = :clinicalSiteId 
                    AND Study_Definition__c = :studyId
                ];

                List<AggregateResult> activePjAggList = [
                    SELECT COUNT(Id) activePj 
                    FROM Patient_Journey__c 
                    WHERE Status__c = 'In Progress' AND Clinical_Site__c = :clinicalSiteId 
                    AND Study_Definition__c = :studyId
                ];

                details.ApheresisCompletedCount = 0;
                details.ManufacturingStartedCount = 0;
                details.IPPackOutCompletedCount = 0;
                details.IPInfusionCompletedCount = 0;

                details.totalJourney = !pjAggList.isEmpty() ? ((Long) pjAggList.get(0).get('pjCount')).intValue() : 0;
                details.activeJourney = !activePjAggList.isEmpty() ? ((Long) activePjAggList.get(0).get('activePj')).intValue() : 0;

                Integer totalJourneyCount = 0;
                for (AggregateResult ar : results) {
                    String stage = (String) ar.get('Current_Stage__c');
                    Integer count = ((Long) ar.get('mileCount')).intValue();
                    totalJourneyCount += count;
                    if (stage.equals('Apheresis Completed')) {
                        details.ApheresisCompletedCount = count;
                    } else if (stage.equals('Manufacturing Started')) {
                        details.ManufacturingStartedCount = count;
                    } else if (stage.equals('IP Pack-Out Completed')) {
                        details.IPPackOutCompletedCount = count;
                    } else if (stage.equals('IP Infusion Completed')) {
                        details.IPInfusionCompletedCount = count;
                    }
                }
                System.debug('totalJourneyCount=>'+totalJourneyCount);
            }
            return details;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class JourneyOverviewDetails {
        @AuraEnabled
        public Integer ApheresisCompletedCount { get; set; }
        @AuraEnabled
        public Integer ManufacturingStartedCount { get; set; }
        @AuraEnabled
        public Integer IPPackOutCompletedCount { get; set; }
        @AuraEnabled
        public Integer IPInfusionCompletedCount { get; set; }
        @AuraEnabled
        public Integer totalJourney { get; set; }
        @AuraEnabled
        public Integer activeJourney { get; set; }
    }
}